# --------------------------------
# Limited Creative - Configuration
# Full Default Configuration at:
# https://github.com/possi/LimitedCreative/blob/master/config.yml
# --------------------------------

store:
    # SeparatedInventoryEnabled
    # Use this option to disable the separated inventories feature, for the case you only need the other features.
    # This option can only changed by reloading the plugin (not via ingame commands).
    # default: true
    enabled: true
    
    # StoreCreative
    # Should the creative-inventory also be stored on disk, when switching to survival?
    # If disabled, the inventory gets cleared every time on switching to creative.
    # default: true
    creative: true
    
    # InventoryFolder
    # The folder inside the datadir-folder (plugin/LimitedCreative) where the inventories are saved to.
    # By default the inventories are saved to "plugin/LimitedCreative/inventories".
    # default: "inventories"
    folder: "inventories"

limit:
    # LimitsEnabled
    # Use this option to disable all drop/pvp/etc. preventions while in creative mode. While you also can get this
    # by giving the "nolimit" permissions, using this option can save you CPU performance. This option can only changed
    # by reloading the plugin (not via ingame commands).
    # default: true
    enabled: true

    # BlockPickup
    # Prevents the pickup of items while in creative mode
    # default: false
    pickup: false
    
    # BlockSign
    # Prevents interacting with signs (right-click), while in creative mode, so trading becomes more difficult.
    # Attention: this will also block useful signs, like Lifts.
    # default: true
    sign: true

region:
    # RegionsEnabled
    # Enables the Feature for "creative-regions". This Feature is automatically disabled, if the required plugin
    # "WorldGuard" (http://dev.bukkit.org/server-mods/worldguard/) isn't found.
    # This option can only changed by reloading the plugin (not via ingame commands).
    # default: true 
    enabled: true

permissions:
    # PermissionsEnabled
    # When enabled, the Permissions will allow selected users to ignore limitations like PvP, Chest-Block, etc.
    # When not enabled, all users are treated equally.
    # Note: The Permission needed for commands, are not affected by this option. So you still need the defined
    #     permissions or op, to use commands, even if this options is disabled!
    # default: false
    enabled: false
    
    # PermissionKeepInventory
    # Disables the limitedcreative.keepinventory-Permission, so you can use the separated-inventories-feature, even
    # if you have a permission plugin that grants ALL permission to you.
    # If Enabled, only players WITHOUT the limitedcreative.keepinventory-Permission, have separated inventories;
    # Players with the permission will have the inventory, like this plugin were not installed.
    # When "PermissionsEnabled" is false, the KeepInventory-Option will act like disabled, even if you set it to true.
    # default: false
    keepinventory: false
