command:
    player: player
    switch:
        survival: Changes the game mode of a player to survival
        creative: Changes the game mode of a player to creative
    config:
        overview: storecreative|blockpickup|blocksign|permissions|perm_keepinventory
    gamemode:
        changed: "{0}'s game mode has been changed"
    option:
        done: Option changed.
exception:
    command:
        lackingpermission: You do not have access to this command
        toomuchparameter: Too much arguments given
        missingparameter: Not enough arguments given
        playernotfound: Player not found
        invalidoption: Unknown option
    config:
        savefail: Failed to write modified configuration to disk
blocked:
    chest: Access to chests is not allowed in creative mode
    sign: To interact with signs is not allowed in creative mode